"""Fetch each firm's icon once and save it into the app's public/ directory.

Deliberately NOT done at render time via a third-party favicon URL: that would
send every viewer's page loads, and the list of firms they look at, to another
company -- and would break the page whenever that service changed. Fetched
once, served from our own origin.

Google's endpoint returns a generic globe for any domain it cannot resolve, so
identical payloads seen across many domains are treated as failures and dropped
rather than shipped as 300 identical logos.
"""
import collections
import hashlib
import pathlib
import time

import requests

from pms_ingest import db

OUT = pathlib.Path(__file__).resolve().parent.parent / "public" / "logos"
# Two sources, tried in order. Google resolves the best icon a site offers and
# is right more often; DuckDuckGo succeeds on sites Google returns nothing for
# (ICICI Prudential among them), so the second pass is worth the requests.
SOURCES = [
    "https://www.google.com/s2/favicons?domain={}&sz=128",
    "https://icons.duckduckgo.com/ip3/{}.ico",
]
# Anything this small is a 1x1 tracking pixel or an error page, not an icon.
MIN_BYTES = 200


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    with db.connect() as conn:
        rows = conn.execute(
            "select distinct website_domain from pms.manager "
            "where website_domain is not null order by 1").fetchall()
    domains = [r["website_domain"] for r in rows]
    print(f"{len(domains)} domains to fetch")

    blobs, failed = {}, []
    for i, d in enumerate(domains, 1):
        if (OUT / f"{d}.png").exists():
            continue        # already have it; do not re-fetch on a second pass
        got = None
        for src in SOURCES:
            try:
                r = requests.get(src.format(d), timeout=15)
                if r.status_code == 200 and len(r.content) >= MIN_BYTES:
                    got = r.content
                    break
            except Exception:
                pass
            time.sleep(0.05)
        if got is None:
            failed.append(d)
        else:
            blobs[d] = got
        if i % 50 == 0:
            print(f"  {i}/{len(domains)}")
        time.sleep(0.05)

    # Drop the placeholder globe: whatever payload repeats across many unrelated
    # domains is not any of their logos.
    counts = collections.Counter(hashlib.sha256(b).hexdigest() for b in blobs.values())
    placeholders = {h for h, n in counts.items() if n >= 5}
    written = 0
    for d, b in blobs.items():
        if hashlib.sha256(b).hexdigest() in placeholders:
            failed.append(d)
            continue
        (OUT / f"{d}.png").write_bytes(b)
        written += 1

    # The app needs to know which logos exist: Vite answers a missing file with
    # index.html at HTTP 200, so an <img> for a firm we lack would download the
    # whole page before failing to decode.
    manifest = OUT.parent.parent / "src" / "data" / "logo-domains.js"
    names = sorted(p.stem for p in OUT.glob("*.png"))
    manifest.write_text(
        "// GENERATED by ingest/scripts_logos.py -- do not edit by hand.\n"
        "//\n"
        "// Which firm domains actually have a logo file in public/logos.\n"
        "export const LOGO_DOMAINS = new Set([\n"
        + "\n".join(f"  '{n}'," for n in names)
        + "\n])\n"
    )
    print(f"manifest written: {manifest} ({len(names)} domains)")

    print(f"\n{written} logos written to {OUT}")
    print(f"{len(failed)} domains had no usable icon "
          f"({len(placeholders)} placeholder payloads detected)")


if __name__ == "__main__":
    main()
